[tool.poetry]
name = "decision-assistant-ao-niiit"
version = "0.1.0"
description = ""
authors = ["ex9000 <ex9000@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flet = "^0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
